Write go-spiffe compatible keys
cert-manager/csi-driver-spiffe pull request #12
Opened 2022-05-03 16:23 UTC by charlieegan3

We are calling Load:
https://github.com/spiffe/go-spiffe/blob/31de176038793c17cf7e77f23e61401160c7d6c9/v2/svid/x509svid/svid.go#L33

This expects an RSA key:
https://github.com/spiffe/go-spiffe/blob/31de176038793c17cf7e77f23e61401160c7d6c9/v2/internal/pemutil/pem.go#L110-L114

This PR when complete will have the csi driver write a different key
format instead.

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

2022-05-03 16:32 UTC, jakexks approved these changes

2022-05-03 16:34 UTC, JoshVanL requested changes
Please add a test to ensure that the [`x509.Load`](https://github.com/spiffe/go-spiffe/blob/31de176038793c17cf7e77f23e61401160c7d6c9/v2/svid/x509svid/svid.go#L33) function call will work on written key pairs from this function.

2022-05-03 16:34 UTC, JoshVanL commented on internal/csi/driver/driver.go
> -		return fmt.Errorf("failed to marshal ECDSA private key for PEM encoding: %w", err)
Please revert, it is still an ECDSA key.

2022-05-03 17:48 UTC, charlieegan3 commented
> Please add a test to ensure that the [`x509.Load`](https://github.com/spiffe/go-spiffe/blob/31de176038793c17cf7e77f23e61401160c7d6c9/v2/svid/x509svid/svid.go#L33) function call will work on written key pairs from this function.

I tried to create a driver and test the `writeKeyPair` function on that but wasn't able to create a mount when running the tests on macOS so have extracted it to a separate function and tested that in f71daf781ee57aab3c0448185398375d701f2661.

Let me know what you think.

2022-05-03 17:51 UTC, JoshVanL commented
@charlieegan3 can we not write a unit test that unit tests the `writeKeyPair`?

`Driver` will be mostly empty, expect for the store. We can use an [`inmemory`](https://github.com/cert-manager/csi-lib/blob/main/storage/memory.go) store.

2022-05-03 17:52 UTC, charlieegan3 commented
> @charlieegan3 can we not write a unit test that unit tests the `writeKeyPair`?
> 
> `Driver` will be mostly empty, expect for the store. We can use an [`inmemory`](https://github.com/cert-manager/csi-lib/blob/main/storage/memory.go) store.

Perhaps I can fashion one without using New. Let me have a play.

2022-05-04 09:35 UTC, charlieegan3 commented
Closing in favour of #13

2022-05-04 09:35 UTC, closed without merging