Add missing --csi-driver-name option to daemonset
cert-manager/csi-driver-spiffe pull request #24
Opened 2023-01-24 09:45 UTC by kesselborn

This was missing in the daemonset but present in the deployment with the confusing effect that the csidriver was listed when listing the csidrivers but reported as missing, when being useD

2023-02-14 09:45 UTC, SgtCoDFish commented
/ok-to-test

2023-02-14 09:46 UTC, SgtCoDFish requested changes

2023-02-14 09:46 UTC, SgtCoDFish commented on deploy/charts/csi-driver-spiffe/Chart.yaml
> +version: v0.2.3
suggestion: I'd rather not change the version in this PR, if possible. I'd rather bump it when we do a new release, in a separate PR!

2023-04-04 11:28 UTC, kesselborn commented
@SgtCoDFish I removed the patch-bump in the `Chart.yaml` file ... is that what is missing to get this merged?

2023-04-04 11:52 UTC, SgtCoDFish approved these changes
/lgtm
/approve

Thanks, yeah, that was the only thing missing. Looks like this arg should definitely be added!

Appreciate the contribution! I'll try to look into getting a release done with this change, but it won't be straight away because there's a lot going on right now. Could be after KubeCon EU!

Thanks again!

2023-04-04 11:53 UTC, merged

2023-04-14 15:16 UTC, SgtCoDFish commented
This is now released in 0.4.0 :tada: